// This file is generated by Slice Machine. Update with care!

import Accordion from './Accordion';
import DemoSimpleHeading from './DemoSimpleHeading';
import FeaturedArticles from './FeaturedArticles';
import HeaderBanner from './HeaderBanner';
import HeroSectionCard from './HeroSectionCard';
import Image from './Image';
import Menu from './Menu';
import ScrollingCards from './ScrollingCards';
import SimpleHeading from './SimpleHeading';
import Text from './Text';
import TopPromotionBanner from './TopPromotionBanner';

export {
	Accordion,
	DemoSimpleHeading,
	FeaturedArticles,
	HeaderBanner,
	HeroSectionCard,
	Image,
	Menu,
	ScrollingCards,
	SimpleHeading,
	Text,
	TopPromotionBanner,
};

export const components = {
	accordion: Accordion,
	demo_simple_heading: DemoSimpleHeading,
	featured_articles: FeaturedArticles,
	logo_cloud: HeaderBanner,
	hero_section_card: HeroSectionCard,
	image: Image,
	menu: Menu,
	scrolling_cards: ScrollingCards,
	simple_heading: SimpleHeading,
	text: Text,
	top_promotion_banner: TopPromotionBanner,
};
