// This file is generated by Slice Machine. Update with care!

import Accordion from './Accordion';
import FeaturedArticles from './FeaturedArticles';
import HeroSectionCard from './HeroSectionCard';
import Image from './Image';
import LogoCloud from './LogoCloud';
import ScrollingCards from './ScrollingCards';
import Text from './Text';

export {
	Accordion,
	FeaturedArticles,
	HeroSectionCard,
	Image,
	LogoCloud,
	ScrollingCards,
	Text,
};

export const components = {
	accordion: Accordion,
	featured_articles: FeaturedArticles,
	hero_section_card: HeroSectionCard,
	image: Image,
	logo_cloud: LogoCloud,
	scrolling_cards: ScrollingCards,
	text: Text,
};
