// This file is generated by Slice Machine. Update with care!

import Accordion from './Accordion';
import CtaSection from './CtaSection';
import FeaturedArticles from './FeaturedArticles';
import FeaturedProducts from './FeaturedProducts';
import HeaderBanner from './HeaderBanner';
import HeroSectionCard from './HeroSectionCard';
import Image from './Image';
import Menu from './Menu';
import Reinsurance from './Reinsurance';
import ScrollingCards from './ScrollingCards';
import Text from './Text';
import TopPromotionBanner from './TopPromotionBanner';

export {
	Accordion,
	CtaSection,
	FeaturedArticles,
	FeaturedProducts,
	HeaderBanner,
	HeroSectionCard,
	Image,
	Menu,
	Reinsurance,
	ScrollingCards,
	Text,
	TopPromotionBanner,
};

export const components = {
	accordion: Accordion,
	cta_section: CtaSection,
	featured_articles: FeaturedArticles,
	featured_products: FeaturedProducts,
	logo_cloud: HeaderBanner,
	hero_section_card: HeroSectionCard,
	image: Image,
	menu: Menu,
	reinsurance: Reinsurance,
	scrolling_cards: ScrollingCards,
	text: Text,
	top_promotion_banner: TopPromotionBanner,
};
